### PR TITLE
Small syntax errors in two files

### PR DESCRIPTION
**Pull request by zxjinn**
Love these functions :thumbsup:

### CODE REVIEW

**Comment by kwilczynski** [comment]
Nice! Thanks a million :)

**Comment by kwilczynski** [comment]
By the way, you gave me an incentive to finish these functions and add a whole bunch more that I use and are not here. It would be nice if you would have the time to help / contribute ;) And again, thanks for the fix, @zxjinn! Much appreciated :)

**Comment by zxjinn** [comment]
I actually was directed to your functions for two specific functions, str2num and str2bool, they both work wonderfully btw. But I run a repo-wide syntax check every time I deploy and noticed those problems. I am by no means a Rubyist, they were just really easy to detect. I'm totally willing to assist, but I can't say I'm any good. :smile:

**Comment by kwilczynski** [comment]
Thanks! No need to be a Rubyist (I am not, I guess) :) If you have an idea for a function, or can think about improvement, or feel like poking some existing ones, then please by any means feel free to do so, plus let me know so I can help :) As I have said, you gave me an incentive to start working on these again -- thank you for that ;]

**Pull request merged**
